#if defined __i386__
#define CLOBBER "%eax", "%edx"
#elif defined __x86_64__
#define CLOBBER "%rax", "%rdx", "%r8", "%r9", "%r10", "%r11", "%r12", "%r13", "%r14", "%r15"
#elif defined __powerpc__ || defined __powerpc64__
#define CLOBBER "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"
#endif


long check_bug37195()
{
	long a0, a1, a2, a3;
	long b0, b1, b2, b3;
	long c0, c1, c2, c3;
	long d0, d1, d2, d3;
	
	a0 = 1; a1 = 2; a2 = 3; a3 = 4;
	
	asm("# ASM 1\n"
		"# %%0 = %0\n"
		"# %%1 = %1\n"
		"# %%2 = %2\n"
		"# %%3 = %3\n"
		"# %%4 = %4\n"
		"# %%5 = %5\n"
		"# %%6 = %6\n"
		"# %%7 = %7\n"
		".ifeqs \"%0\",\"%4\"\n"
		".error \"ASM 1: %%0 and %%4 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%5\"\n"
		".error \"ASM 1: %%0 and %%5 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%6\"\n"
		".error \"ASM 1: %%0 and %%6 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%7\"\n"
		".error \"ASM 1: %%0 and %%7 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%4\"\n"
		".error \"ASM 1: %%1 and %%4 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%5\"\n"
		".error \"ASM 1: %%1 and %%5 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%6\"\n"
		".error \"ASM 1: %%1 and %%6 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%7\"\n"
		".error \"ASM 1: %%1 and %%7 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%4\"\n"
		".error \"ASM 1: %%2 and %%4 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%5\"\n"
		".error \"ASM 1: %%2 and %%5 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%6\"\n"
		".error \"ASM 1: %%2 and %%6 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%7\"\n"
		".error \"ASM 1: %%2 and %%7 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%4\"\n"
		".error \"ASM 1: %%3 and %%4 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%5\"\n"
		".error \"ASM 1: %%3 and %%5 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%6\"\n"
		".error \"ASM 1: %%3 and %%6 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%7\"\n"
		".error \"ASM 1: %%3 and %%7 are both equal to %3\"\n"
		".endif\n"
		: "=&rm" (b0), "=&rm" (b1), "=&rm" (b2), "=&rm" (b3)
		: "rm" (a0), "rm" (a1), "rm" (a2), "rm" (a3)
		: CLOBBER
		);
	asm("# ASM 2\n"
		"# %%0 = %0\n"
		"# %%1 = %1\n"
		"# %%2 = %2\n"
		"# %%3 = %3\n"
		"# %%4 = %4\n"
		"# %%5 = %5\n"
		"# %%6 = %6\n"
		"# %%7 = %7\n"
		".ifeqs \"%0\",\"%4\"\n"
		".error \"ASM 2: %%0 and %%4 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%5\"\n"
		".error \"ASM 2: %%0 and %%5 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%6\"\n"
		".error \"ASM 2: %%0 and %%6 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%7\"\n"
		".error \"ASM 2: %%0 and %%7 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%4\"\n"
		".error \"ASM 2: %%1 and %%4 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%5\"\n"
		".error \"ASM 2: %%1 and %%5 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%6\"\n"
		".error \"ASM 2: %%1 and %%6 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%7\"\n"
		".error \"ASM 2: %%1 and %%7 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%4\"\n"
		".error \"ASM 2: %%2 and %%4 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%5\"\n"
		".error \"ASM 2: %%2 and %%5 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%6\"\n"
		".error \"ASM 2: %%2 and %%6 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%7\"\n"
		".error \"ASM 2: %%2 and %%7 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%4\"\n"
		".error \"ASM 2: %%3 and %%4 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%5\"\n"
		".error \"ASM 2: %%3 and %%5 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%6\"\n"
		".error \"ASM 2: %%3 and %%6 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%7\"\n"
		".error \"ASM 2: %%3 and %%7 are both equal to %3\"\n"
		".endif\n"
		: "=&rm" (c0), "=&rm" (c1), "=&rm" (c2), "=&rm" (c3)
		: "rm" (b0), "rm" (b1), "rm" (b2), "rm" (b3)
		: CLOBBER
		);
	asm("# ASM 3\n"
		"# %%0 = %0\n"
		"# %%1 = %1\n"
		"# %%2 = %2\n"
		"# %%3 = %3\n"
		"# %%4 = %4\n"
		"# %%5 = %5\n"
		"# %%6 = %6\n"
		"# %%7 = %7\n"
		".ifeqs \"%0\",\"%4\"\n"
		".error \"ASM 3: %%0 and %%4 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%5\"\n"
		".error \"ASM 3: %%0 and %%5 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%6\"\n"
		".error \"ASM 3: %%0 and %%6 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%0\",\"%7\"\n"
		".error \"ASM 3: %%0 and %%7 are both equal to %0\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%4\"\n"
		".error \"ASM 3: %%1 and %%4 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%5\"\n"
		".error \"ASM 3: %%1 and %%5 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%6\"\n"
		".error \"ASM 3: %%1 and %%6 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%1\",\"%7\"\n"
		".error \"ASM 3: %%1 and %%7 are both equal to %1\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%4\"\n"
		".error \"ASM 3: %%2 and %%4 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%5\"\n"
		".error \"ASM 3: %%2 and %%5 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%6\"\n"
		".error \"ASM 3: %%2 and %%6 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%2\",\"%7\"\n"
		".error \"ASM 3: %%2 and %%7 are both equal to %2\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%4\"\n"
		".error \"ASM 3: %%3 and %%4 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%5\"\n"
		".error \"ASM 3: %%3 and %%5 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%6\"\n"
		".error \"ASM 3: %%3 and %%6 are both equal to %3\"\n"
		".endif\n"
		".ifeqs \"%3\",\"%7\"\n"
		".error \"ASM 3: %%3 and %%7 are both equal to %3\"\n"
		".endif\n"
		: "=&rm" (d0), "=&rm" (d1), "=&rm" (d2), "=&rm" (d3)
		: "rm" (c0), "rm" (c1), "rm" (c2), "rm" (c3)
		: CLOBBER
		);
	
	if (a0 == d0 && a1 == d1 && a2 == d2 && a3 == d3) return b0;
	else return c0;
}
